[project]
name = "<project-name>"
version = "0.1.0"
description = "<project-description>"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = [
    "ipython>=9.2.0",
]

[tool.setuptools]
packages = ["<src-dir>"]
